[package]
name = "markown-format"
version = "0.1.0"
authors = ["Wonko <wonko@hanstool.org>"]
edition = "2021"

[dependencies]
anyhow = "1.0.70"
lazy_static = "1.4.0"
markdown = "0.3.0"
regex = "1.8.0"
