[package]
name = "markownfmt"
version = "0.1.0"
authors = ["Wonko <wonko@hanstool.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
markdown = "0.3"
regex = "*"
lazy_static = "*"
anyhow = "1.0.70"
